#ifndef CORRELATION_PARAM_H
#define CORRELATION_PARAM_H

#define CORRELATION_OPERATOR_MAX_OFFSETS (51*51)
#define CORRELATION_OPERATOR_LIST_SIZE (2*CORRELATION_OPERATOR_MAX_OFFSETS)

#define MACRO_STR_HELPER(x) #x
#define MACRO_STR(x) MACRO_STR_HELPER(x)
#endif

